ExamenZapatillas/Models/ErrorViewModel.cs
namespace ExamenZapatillas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExamenZapatillas/Models/ImagenZapatilla.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamenZapatillas.Models
{
    [Table("IMAGENESZAPASPRACTICA")]
    public class ImagenZapatilla
    {
        [Key]
        [Column("IDIMAGEN")]
        public int IdImagen { get; set; }
        [Column("IDPRODUCTO")]
        public int IdProducto { get; set; }
        [Column("IMAGEN")]
        public string NombreImagen { get; set; }
    }
}

ExamenZapatillas/Models/ModelImagenZapa.cs
namespace ExamenZapatillas.Models
{
    public class ModelImagenZapa
    {
        public Zapatilla zapatilla { get; set; }
        public ImagenZapatilla imagen { get; set; }
        public int numRegistros { get; set; }
    }
}

ExamenZapatillas/Models/ModelPaginarImagen.cs
namespace ExamenZapatillas.Models
{
    public class ModelPaginarImagen
    {
        public Zapatilla zapatilla { get; set; }
        public ImagenZapatilla Imagen { get; set; }
        public int numRegistros { get; set; }
    }
}

ExamenZapatillas/Models/VistaImagenes.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace ExamenZapatillas.Models
{
    [Table("V_IMAGENES")]
    public class VistaImagenes
    {
        [Key]
        [Column("IDIMAGEN")]
        public int IdImagen { get; set; }
        [Column("IDPRODUCTO")]
        public int IdProducto { get; set; }
        [Column("IMAGEN")]
        public string Imagen { get; set; }
        [Column("POSICION")]
        public int Posicion { get; set; }
    }
}

ExamenZapatillas/Models/VistaZapas.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamenZapatillas.Models
{
    [Table("V_ZAPAS_INDIVIDUAL")]
    public class VistaZapas
    {
		[Key]
		[Column("IDPRODUCTO")]
		public int IdProducto { get; set; }
		[Column("POSICION")]
		public int Posicion { get; set; }
		[Column("NOMBRE")]
		public string Nombre { get; set; }
		[Column("DESCRIPCION")]
		public string Descripcion { get; set; }
		[Column("PRECIO")]
		public int Precio { get; set; }
		[Column("IDIMAGEN")]
		public int IdImagen { get; set; }
		[Column("IMAGEN")]
		public string Imagen { get; set; }

    }
}
/*
 CREATE VIEW V_ZAPAS_INDIVIDUAL
AS
	SELECT CAST(
	ROW_NUMBER() OVER (ORDER BY Z.IDPRODUCTO) AS INT)
	AS POSICION,
	ISNULL(Z.IDPRODUCTO, 0) AS IDPRODUCTO, Z.NOMBRE,
	Z.DESCRIPCION, Z.PRECIO, I.IDIMAGEN, I.IMAGEN
	FROM ZAPASPRACTICA Z
	INNER JOIN IMAGENESZAPASPRACTICA I
	ON Z.IDPRODUCTO=I.IDPRODUCTO
GO
*/

ExamenZapatillas/Models/Zapatilla.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamenZapatillas.Models
{
    [Table("ZAPASPRACTICA")]
    public class Zapatilla
    {
        [Key]
        [Column("IDPRODUCTO")]
        public int IdZapatilla { get; set; }
        [Column("NOMBRE")]
        public string Nombre { get; set; }
        [Column("DESCRIPCION")]
        public string Descripcion { get; set; }
        [Column("PRECIO")]
        public int Precio { get; set; }
    }
}

ExamenZapatillas/Controllers/HomeController.cs
using ExamenZapatillas.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ExamenZapatillas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExamenZapatillas/Controllers/PaginacionController.cs
using ExamenZapatillas.Models;
using ExamenZapatillas.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace ExamenZapatillas.Controllers
{
    public class PaginacionController : Controller
    {
        private RepositoryZapatillas repo;
        public PaginacionController(RepositoryZapatillas repo)
        {
            this.repo = repo;
        }

        /*METODO PARA PAGINAR UNA SOLA ZAPATILLA
        public async Task<IActionResult> PaginarZapatilla
            (int? posicion, int idzapa)
        {
            if(posicion == null)
            {
                posicion = 1;
            }
            ModelPaginarImagen model = await
                this.repo.GetImagenZapaAsync
                (posicion.Value, idzapa);
            Zapatilla zapa = await this.repo.FindZapatilla(idzapa);

            ViewData["ZAPATILLASELECCIONADA"] = zapa;
            ViewData["REGISTROS"] = model.numRegistros;
            ViewData["ZAPA"] = idzapa;

            int siguiente = posicion.Value + 1;

            if (siguiente > model.numRegistros)
            {
                siguiente = model.numRegistros;
            }

            int anterior = posicion.Value - 1;
            if (anterior < 1)
            {
                anterior = 1;
            }

            ViewData["ULTIMO"] = model.numRegistros;
            ViewData["SIGUIENTE"] = siguiente;
            ViewData["ANTERIOR"] = anterior;
            ViewData["POSICION"] = posicion;

            return View(model.Imagen);
        }
        */

        
    }
}

ExamenZapatillas/Controllers/ZapatillasController.cs
using ExamenZapatillas.Models;
using ExamenZapatillas.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace ExamenZapatillas.Controllers
{
    public class ZapatillasController : Controller
    {
        private RepositoryZapatillas repoZapas;

        public ZapatillasController(RepositoryZapatillas repoZapas)
        {
            this.repoZapas = repoZapas;
        }
    
        //mostraremos una vista con una tabla de zapatillas
        public async Task<IActionResult> Index()
        {
            List<Zapatilla> zapas = await
                this.repoZapas.GetZapas();
            return View(zapas);
        }

        public async Task<IActionResult> Detalles
            (int? posicion, int idzapa)
        {
            if (posicion == null)
            {
                posicion = 1;
            }

            ModelPaginarImagen model = await
                this.repoZapas.GetImagenZapaAsync(posicion.Value, idzapa);

            ViewData["ZAPATILLASELECCIONADA"] = model.zapatilla;
            return View();
        }
       
        public async Task<IActionResult> _ImagenesPartial
            (int? posicion, int idzapa)
        {
            if (posicion == null)
            {
                posicion = 1;
            }
            ModelPaginarImagen model = await
                this.repoZapas.GetImagenZapaAsync
                (posicion.Value, idzapa);
            Zapatilla zapa = await this.repoZapas.FindZapatilla(idzapa);

            ViewData["ZAPATILLASELECCIONADA"] = zapa;
            ViewData["REGISTROS"] = model.numRegistros;
            ViewData["ZAPA"] = idzapa;

            int siguiente = posicion.Value + 1;

            if (siguiente > model.numRegistros)
            {
                siguiente = model.numRegistros;
            }

            int anterior = posicion.Value - 1;
            if (anterior < 1)
            {
                anterior = 1;
            }

            ViewData["ULTIMO"] = model.numRegistros;
            ViewData["SIGUIENTE"] = siguiente;
            ViewData["ANTERIOR"] = anterior;
            ViewData["POSICION"] = posicion;

            return View(model.Imagen);
        }

        public async Task<IActionResult> InsertarImagenes()
        {
            List<Zapatilla> zapas = await 
                this.repoZapas.GetZapas();
            return View(zapas);
        }

        [HttpPost]
        public async Task<IActionResult> InsertarImagenes
            (int idzapa, List<string> imagenes)
            /*(int idzapa, string imagen)*/
        {
            //await this.repoZapas.InsertarImagen(idzapa, imagen);

            foreach (string imagen in imagenes)
            {
                await this.repoZapas.InsertarImagen(idzapa, imagen);
            }
            return RedirectToAction("Index");
        }
    }
}

ExamenZapatillas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ExamenZapatillas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExamenZapatillas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExamenZapatillas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExamenZapatillas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Zapatillas" asp-action="Index">Zapatillas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Zapatillas" asp-action="InsertarImagenes">Nueva imagen</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ExamenZapatillas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ExamenZapatillas/Views/Zapatillas/Detalles.cshtml
@*@model ImagenZapatilla*@

@{
    Zapatilla zapa = ViewData["ZAPATILLASELECCIONADA"] as Zapatilla;
}

<h1>Zapatila:</h1>

<div class="card">
    <div class="card-header">
        Nombre: @zapa.Nombre
    </div>
    <div class="card-body">
        
        <p class="card-text">@zapa.Descripcion</p>
        
    </div>

    <div class="card-footer">
       Precio: @zapa.Precio
    </div>
</div>



<div id="contenido"></div>
@section Scripts {
    <script>
        function loadImagenPaginacion(posicion) {
            $(function () {
                $("#contenido").load("/Zapatillas/_ImagenesPartial?posicion="
                    + posicion + "&idzapa=" + @zapa.IdZapatilla);
            });
        }

        loadImagenPaginacion(1);
    </script>
}

ExamenZapatillas/Views/Zapatillas/Index.cshtml
@model List<Zapatilla>

<h1>Lista de Zapatillas</h1>

<table class="table table-bordered">
    <tbody>
        @foreach(Zapatilla z in Model)
        {
            <tr>
                <td>
                    <a asp-controller="Zapatillas" asp-action="Detalles"
                    class="btn btn-dark" asp-route-idzapa="@z.IdZapatilla">
                        @z.Nombre
                    </a>
                    
                </td>
            </tr>
        }
    </tbody>
</table>

ExamenZapatillas/Views/Zapatillas/InsertarImagenes.cshtml
@*model List<Zapatilla>

<h1>Insertar nuevas imágenes:</h1>

<button id="nuevoinput" class="btn btn-info">Añadir caja</button>
<br /><br />

<form method="post" id="imageForm">

    <button class="btn btn-success">Insertar Imagenes!</button>
    <br />
    <label>Seleccione la zapatilla</label>
    <select name="idzapa" class="form-control">
        @foreach (Zapatilla zapa in Model)
        {
            <option value="@zapa.IdZapatilla">
                @zapa.Nombre
            </option>
        }
    </select>
    <br />

    <div id="inputsContainer">
        <label>Imagenes</label>
        <input type="text" name="imagenes[0]" class="form-control" /> <!-- Cambiado el nombre del input principal -->
    </div>
</form>

@section Scripts {
    <script>
        var contadorInputs = 1;

        function agregarNuevoInput() {
            contadorInputs++;
            var nuevoInput = document.createElement('input');
            nuevoInput.type = 'text';
            nuevoInput.name = 'imagenes[' + contadorInputs + ']'; // Modificado el nombre del input dinámico
            nuevoInput.className = 'form-control';
            document.getElementById('inputsContainer').appendChild(nuevoInput);
        }

        document.getElementById('nuevoinput').addEventListener('click', function () {
            agregarNuevoInput();
        });

        // Función para recopilar los valores de los inputs dinámicos y enviarlos con el formulario
        function enviarFormulario() {
            var form = document.getElementById('imageForm');
            var inputs = document.querySelectorAll('#inputsContainer input');
            inputs.forEach(function (input, index) {
                input.name = 'imagenes[' + index + ']'; // Actualizar el nombre de los inputs dinámicos para la serialización correcta
            });
            form.submit(); // Enviar el formulario
        }
    </script>
}
@model List<Zapatilla>

<h1>Insertar nuevas imágenes:</h1>

<button id="nuevoinput" class="btn btn-info">Añadir caja</button>
<br /><br />

<form method="post" id="imageForm">
    
    <button class="btn btn-success">Insertar Imagenes!</button>
    <br />
    <label>Seleccione la zapatilla</label>
    <select name="idzapa" class="form-control">
        @foreach (Zapatilla zapa in Model)
        {
            <option value="@zapa.IdZapatilla">
                @zapa.Nombre
            </option>
        }
    </select>
    <br />

    <div id="inputsContainer">
        <label>Imagenes</label>
        <input type="text" name="imagen" class="form-control" />
    </div>
</form>

@section Scripts {
    <script>
        var contadorInputs = 1;

        function agregarNuevoInput() {
            contadorInputs++;
            var nuevoInput = document.createElement('input');
            nuevoInput.type = 'text'; 
            nuevoInput.name = 'imagen' + contadorInputs; 
            nuevoInput.className = 'form-control'; 
            document.getElementById('inputsContainer').appendChild(nuevoInput); 
        }

        document.getElementById('nuevoinput').addEventListener('click', function () {
            agregarNuevoInput();
        });
    </script>
}

FORMULARIO NORMAL
<form method="post">
    <br />
    <button class="btn btn-success">Insertar Imagenes!</button>

    <label>Seleccione la zapatilla</label>
    <select name="idzapa" class="form-control">
        @foreach (Zapatilla zapa in Model)
        {
            <option value="@zapa.IdZapatilla">
                @zapa.Nombre
            </option>
        }
    </select>
    <br />

    <label>Imagen 1</label>
    <input type="text" name="imagen" class="form-control" />


</form>*@



@model List<Zapatilla>

<h1>Insertar nuevas imágenes:</h1>

<button id="nuevoinput" class="btn btn-info">Añadir caja</button>
<br />
<br />

<form method="post" id="imageForm">

    <button class="btn btn-success" type="button" onclick="enviarFormulario()">Insertar Imagenes!</button> 
    <br />
    <label>Seleccione la zapatilla</label>
    <select name="idzapa" class="form-control">
        @foreach (Zapatilla zapa in Model)
        {
            <option value="@zapa.IdZapatilla">
                @zapa.Nombre
            </option>
        }
    </select>
    <br />

    <div id="inputsContainer">
        <label>Imagenes</label>
        <input type="text" name="imagenes[0]" class="form-control" />
    </div>
</form>

@section Scripts {
    <script>
        var contadorInputs = 1;

        function agregarNuevoInput() {
            contadorInputs++;
            var nuevoInput = document.createElement('input');
            nuevoInput.type = 'text';
            nuevoInput.name = 'imagenes[' + contadorInputs + ']'; 
            nuevoInput.className = 'form-control';
            document.getElementById('inputsContainer').appendChild(nuevoInput);
        }

        document.getElementById('nuevoinput').addEventListener('click', function () {
            agregarNuevoInput();
        });

        function enviarFormulario() {
            var form = document.getElementById('imageForm');
            var inputs = document.querySelectorAll('#inputsContainer input');
            inputs.forEach(function (input, index) {
                input.name = 'imagenes[' + index + ']'; 
            });
            form.submit();
        }
    </script>
}

ExamenZapatillas/Views/Zapatillas/_ImagenesPartial.cshtml
@model ImagenZapatilla

@{
    Zapatilla zapa = ViewData["ZAPATILLASELECCIONADA"] as Zapatilla;
}

@*aqui la patial*@
<p>Imagen @ViewData["POSICION"] de @ViewData["ULTIMO"]</p>
<ul class="list-group list-group-horizontal">
    <li class="list-group-item">
        @*<a asp-controller="Paginacion"
           asp-action="PaginarZapatilla"
           asp-route-posicion="1"
           asp-route-idzapa="@ViewData["ZAPA"]">
            Primero
        </a>*@
        <button onclick="loadImagenPaginacion(1)" class="btn">
            Primero
        </button>
    </li>
    <li class="list-group-item">
        @*<a asp-controller="Paginacion"
           asp-action="PaginarZapatilla"
           asp-route-posicion="@ViewData["ANTERIOR"]"
           asp-route-idzapa="@ViewData["ZAPA"]">
            Anterior
        </a>*@
        <button onclick="loadImagenPaginacion(@ViewData["ANTERIOR"])" class="btn">
            Anterior
        </button>
    </li>
    <li class="list-group-item">
        @*<a asp-controller="Paginacion"
           asp-action="PaginarZapatilla"
           asp-route-posicion="@ViewData["SIGUIENTE"]"
           asp-route-idzapa="@ViewData["ZAPA"]">
            Siguiente
        </a>*@
        <button onclick="loadImagenPaginacion(@ViewData["SIGUIENTE"])" class="btn">
            Siguiente
        </button>
    </li>
    <li class="list-group-item">
        @*<a asp-controller="Paginacion"
           asp-action="PaginarZapatilla"
           asp-route-posicion="@ViewData["ULTIMO"]"
           asp-route-idzapa="@ViewData["ZAPA"]">
            Ultimo
        </a>*@

        <button onclick="loadImagenPaginacion(@ViewData["ULTIMO"])" class="btn">
            Ultimo
        </button>
    </li>
</ul>

<div class="card" id="container">

    <div class="card-body">

        <img src="@Model.NombreImagen" style="width:100px; height:100px;"

    </div>

</div>